# Generated by Django 5.1 on 2024-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zubayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_name',
            field=models.CharField(max_length=20),
        ),
    ]
